# Generated by Django 4.1.3 on 2023-10-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_likeforpost_target_remove_likeforpost_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='poster_path',
            field=models.CharField(default=230, max_length=255, verbose_name='タイトル'),
            preserve_default=False,
        ),
    ]
