# Generated by Django 4.1.3 on 2023-10-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_review_spoiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=3200000, verbose_name='本文'),
        ),
    ]
