# Generated by Django 4.1.3 on 2023-10-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=320000, verbose_name='本文'),
        ),
    ]
