# Generated by Django 4.1.3 on 2023-10-18 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_mylist_options_mylist_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='backdrop_path',
        ),
        migrations.RemoveField(
            model_name='review',
            name='poster_path',
        ),
    ]
