# Generated by Django 4.1.3 on 2023-10-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_review_backdrop_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='spoiler',
            field=models.BooleanField(default=False, verbose_name='ネタバレ'),
        ),
    ]
