# Generated by Django 4.1.3 on 2023-10-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='公開'),
        ),
    ]
