# Generated by Django 4.1.3 on 2023-10-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_customuser_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nick_name',
            field=models.CharField(blank=True, default='無名さん', max_length=30, null=True, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.DateTimeField(blank=True, default='2023-10-24', null=True, verbose_name='生年月日'),
        ),
    ]
