# Generated by Django 5.1.1 on 2024-12-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_customuser_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.DateTimeField(blank=True, default='2024-12-30', null=True, verbose_name='生年月日'),
        ),
    ]
